config/routes.rb
Rails.application.routes.draw do
  root 'posts#show'
  get '/login' => 'sessions#index'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#delete'
  resources :posts do
    resources :post_votes
  end
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  has_many :post_votes
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  # def post_vote_score
  #   score = PostVote.find_by(self.post_id
  # end
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt

  has_many :post_votes
  has_many :posts
  has_many :comments

  validates :name, length: {minimum: 3}
  validates :password, length: {minimum: 3}
  validates :email, presence: true

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def authenticate(plaintext_password)
    self.password == plaintext_password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper # I know i showed this, but it's not typically done.  But yeah, you _can_ do it.   Both of your methods in there would probably be appropriate in the Controller anyway.
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find_by(id: params[:post_id])
    @comments = @post.comments
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    if !!@comment # not strictly necessary. you're coercing to Boolean which is good communication
      @comment.update(body: params[:body])
      redirect_to post_comments_path
    else
      redirect_to :back
    end
  end

  def new
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.new
  end

  def create
    # I think this might be a bit nicer...
    # @comment = Post.find(params[:post_id]).comments.build(comment_params)
    @comment = Comment.new(post_id: params[:post_id], user_id: session[:user_id], body: comment_params[:body])
    if @comment.save
      redirect_to post_comments_path
    else
      flash[:notice] = "There was something wrong with your submission"
      redirect new_post_comment_path
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    redirect_to post_comments_path
  end

  private

  def comment_params
    # See above in #create
    # params.require(:comment.permit(:body).merge(user: User.find(params[:user_id]))
    params.require(:comment).permit(:body)
  end
end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
  def edit
    # This is a classic underutilization of ActiveRecord
    #
    # Post.find(params[:post_id]).postvotes.create
    #
    # but that makes me ask the question: what's a PostVote?  You could give
    # that a much more informative name like: "Voting" -> "VotingsController"
    #
    # But then again, it also might be much better for there to be a Vote class
    # which has a value (+1 / -1).  Thus we could do:
    #
    # Post.find(:id).votes.map(&:value).reduce(:+)
    post_vote = PostVote.find_by(post_id: params[:post_id])
    old_score = post_vote.score
    post_vote.update(score: old_score+1)
    redirect_to root_path
  end

  def destroy
    post_vote = PostVote.find_by(post_id: params[:post_id])
    old_score = post_vote.score
    post_vote.update(score: old_score-1)
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      PostVote.create(user_id: session[:user_id], post_id: @post.id)
      redirect_to @post
    else
      flash[:notice] = "There was a problem submitting your post"
    end
  end

  private
  def post_params
    params.require(:post).permit(:body, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def create
    @user = User.find_by(name: params[:name])
    if !!@user # practiacally, people don't do that !! coercion.  i rarely see it.
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "There was a problem with your UserName or Password"
      redirect_to login_path
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:show]

  def show
    @user = User.find_by(id: session[:user_id])
    @posts = @user.posts
    @comments = @user.comments
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = "There was a problem with your UserName or Password"
    end
  end

  def edit
    @user = User.find_by(id: session[:user_id])
  end

  def update
    @user = User.find_by(id: session[:user_id])
    if @user.authenticate(params[:user][:password])
      @user.update(user_params)
      redirect_to user_path
    else
      flash[:notice] = "Your password was incorrect"
      redirect_to edit_user_path
    end
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def require_logged_in
    redirect_to root_path unless is_authenticated?
  end

  def is_authenticated?
    return !!session[:user_id]
  end
end

app/views/comments/edit.html.erb
<h1>This is to edit a comment</h1>

<%#NOt correct.  This should be `form_for [@post, @comment]`, that would build the URL for you %>
<%= form_tag post_comment_path, method: :put do %>
  <%= label_tag :comment%>
  <%= text_area_tag :body %> <br>
  <%= submit_tag "Edit Comment" %>
<% end %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/comments/index.html.erb
<h1>This should be the name of the post: <%= @post.body %></h1>
<h2>These are comments:</h2>
 <% if !!session[:user_id] %>
  <%= link_to "Create a Comment", new_post_comment_path %>
 <% end %>
<% @comments.each do |c| %>
  <%# a helper might be nice..... c.is_current_user? %>
  <% if c.user_id == session[:user_id] %>
    <%= link_to "Edit Comment", edit_post_comment_path(@post, c.id) %>
    <%= link_to "Delete Comment", post_comment_path(@post, c.id), method: :delete, data: { confirm: "Are you Sure?"} %>
  <% end %>
  <li><%= c.body %></li>
<% end %>

app/views/comments/new.html.erb
<h1>This is a form to create new Comments</h1>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %> <br>
  <%= f.submit "Create Post" %>
<% end %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsOnRails</title>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h1>Create a new Post here:</h1>
<%= form_for @post do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %> <br>
  <%= f.label :url %>
  <%= f.text_field :url %> <br>
  <%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<%= link_to "Login", login_path %>
<%= link_to "SignUp",  new_user_path %>
<h1>Posts</h1>
<% @posts.each do |p| %>
<ul>
  <li><%= link_to  p.body, p.url %></li>
  <% p.post_votes.each do |v| %>
  <div class="votes-section">
    <div class="upvote"><%= link_to "upvote", edit_post_post_vote_path(p.id, v.post_id) %></div>
    <span class="score"><%= v.score %></span>
    <div class="downvote"><%= link_to "down vote", post_post_vote_path(p.id, v.id), method: "delete" %></div>
  </div>
  <% end %>
  <ul>
    <li><%=link_to "Comments", post_comments_path(p.id) %></li>
  </ul>
</ul>

<% end %>

app/views/users/edit.html.erb
<h1>This is an edit user page</h1>
<%= form_for @user, method: "put" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>
  <%= f.label :email %>
  <%= f.text_field :email %> <br>
  <%= f.label :password %>
  <%= f.password_field :password %> <br>
  <%= f.submit "Edit!" %>
<% end %>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/users/new.html.erb
<h1>This is a NEW user form</h1>
<%= form_for @user do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>
  <%= f.label :email %>
  <%= f.text_field :email %> <br>
  <%= f.label :password %>
  <%= f.password_field :password %> <br>
  <%= f.submit "Create" %>
<% end %>

<%# nice use of this thing...%>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/users/show.html.erb
<h1>This is a profile page of <%= @user.name %></h1>
<h2>Posts:</h2>

<div class="profile-posts">
  <% @posts.each do |p| %>
    <% @comments.each do |c| %>
    <p>POST: <%= p.body %></p>
    <p>COMMENT: <%= c.body %></p>
    <% end %>
  <% end %>
</div>

<%= link_to "Logout",  logout_path, method: :delete %>
<%= link_to "Update Profile", edit_user_path %>
<%= link_to "Delete Profile", user_path, method: :delete %>
<%=  link_to "Create a Post", new_post_path %>